stages:
  - build
  - test
  - code_quality
  - deploy

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: code_quality
  image: docker:stable
  services:
    - name : docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths: [gl-code-quality-report.json]
  tags:
    - csci5408grp14

backend-build-job:
  stage: build
  image: maven:latest
  services:
    - docker:dind
  script:
    - chmod 777 -R FoodBuddy_DevRole
    - cd FoodBuddy_DevRole/backEnd/foodBuddy/foodBuddy
    - mvn clean install 
  artifacts:
    paths:
      - FoodBuddy_DevRole/backEnd/foodBuddy/target
  tags:
    - csci5408grp14

backend-test-job:
  stage: test
  image: maven:latest
  script:
    - cd FoodBuddy_DevRole/backEnd/foodBuddy/foodBuddy
    - mvn test
  tags:
    - csci5408grp14

frontend-build-job:
  stage: build
  image: node:latest
  script:
    - cd FoodBuddy_DevRole/FrontEnd
    - npm install
    - unset CI 
    - npm run build
  tags:
    - csci5408grp14
  artifacts:
    paths:
      - FoodBuddy_DevRole/FrontEnd/build/
deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y sshpass
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no /builds/courses/2023-winter/csci-5308/group14/FoodBuddy_DevRole/backEnd/foodBuddy/target/* $SSH_USER@$HOST_IP:/home/csci5308vm14/foodbuddy/backend
  tags:
    - csci5408grp14
