stages:
  - build
  - test
  - code_quality

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: code_quality
  image: docker:stable
  services:
    - name : docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  artifacts:
    paths: [gl-code-quality-report.json]
  tags:
    - csci5408grp14

backend-build-job:
  stage: build
  image: maven:latest
  services:
    - docker:dind
  script:
    - chmod 777 -R FoodBuddy_DevRole
    - cd FoodBuddy_DevRole/backEnd/foodBuddy
    - mvn clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - FoodBuddy_DevRole/backEnd/foodBuddy/target
  tags:
    - csci5408grp14

backend-test-job:
  stage: test
  image: maven:latest
  script:
    - cd FoodBuddy_DevRole/backEnd/foodBuddy
    - mvn test
  tags:
    - csci5408grp14

frontend-build-job:
  stage: build
  image: node:latest
  script:
    - cd FoodBuddy_DevRole/FrontEnd
    - npm install
    - unset CI 
    - npm run build
  tags:
    - csci5408grp14
  artifacts:
    paths:
      - FoodBuddy_DevRole/FrontEnd/build/
