stages:
  - build
  - test
  - code_quality
  
include:
  - template: Code-Quality.gitlab-ci.yml

backend-build-job:
  stage: build
  script:
    - chmod 777 -R FoodBuddy_DevRole
    - cd FoodBuddy_DevRole/backEnd/foodBuddy
    - mvn clean install -Dmaven.test.skip=true
  tags:
    - CSCI5308Grp14

backend-test-job:
  stage: test
  script:
    - cd FoodBuddy_DevRole/backEnd/foodBuddy
    - mvn test
  tags:
    - CSCI5308Grp14

frontend-build-job:
  stage: build
  script:
    - export PATH=/home/csci5308vm14/.nvm/versions/node/v18.15.0/bin/:$PATH
    - cd FoodBuddy_DevRole/FrontEnd
    - npm install
    - unset CI 
    - npm run build
  tags:
    - CSCI5308Grp14

code_quality:
  stage: code_quality
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [gl-code-quality-report.json]



