stages:
  - build

build-job:
  stage: build
  script:
    - chmod 777 -R FoodBuddy_DevRole
    - cd FoodBuddy_DevRole/backEnd/foodBuddy
    - mvn clean install -Dmaven.test.skip=true
  tags:
    - CSCI5308Grp14