stages:
  - build

build-job:
  stage: build
  script:
    - echo "Script Started from: ${PWD}"
    - cd ./FoodBuddy_DevRole/backEnd/foodBuddy
    - chmod 777 -R ./FoodBuddy_DevRole/backEnd/foodBuddy
    - echo "Script executed from: ${PWD}"
    - mvn clean install
  tags:
    - CSCI5308Grp14