server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: Qwerty@123
    url: jdbc:mysql://localhost:3306/foodBuddy
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


