server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: Lalith@1999
    url: jdbc:mysql://localhost:3306/foodbuddy
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


