server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: Guddi@2000
    url: jdbc:mysql://localhost:3306/foodbuddy
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mail:
  host: smtp.gmail.com
  port: 587
  username: foodbuddy.asdc5308@gmail.com
  password: password@asdc5308
  protocol: smtp
  tls: true
  properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

